spring.application.name=eureka-server-2
spring.security.user.name=eureka
spring.security.user.password=eureka

server.port=8762

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://eureka:eureka@localhost:8761/eureka/
eureka.server.enable-self-preservation=false
